### PR TITLE
[#70] Basic identity

### PR DESCRIPTION
**Pull request by lx0f**
Basic Identity System with register, login, logout, and Session management. Should mostly fulfill #70 🍡 Haven't added E2E tests yet though

### Changes
Classes:
- User
- AuthDbContext
- SessionVariable: A static class to provide a standard session
  interface throughout the application. Any new additions to the session
  have to be registered here.

Pages:
- /Register
- /Login
- /Logout
- /Whoami: For us to verify user status (logged in or signed out)

### CODE REVIEW

**Review by Ronandt — APPROVED** [review]
For base it's fine :D 👍

**Comment by HProsperouS** [comment]
GOOD

**Review by HProsperouS — APPROVED** [review]
LW

**Comment by lx0f** [comment]
Thanks everyone 💯

**Pull request merged**
